repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-json
      - id: check-merge-conflict
      - id: mixed-line-ending

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        files: \.(js|jsx|ts|tsx|css|scss|json|md)$
        args: ['--write']

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.56.0
    hooks:
      - id: eslint
        files: \.(js|jsx|ts|tsx)$
        args: ['--fix', '--max-warnings=0']
        additional_dependencies:
          - eslint@8.56.0
          - eslint-config-react-app
          - eslint-plugin-react
          - eslint-plugin-react-hooks
          - eslint-plugin-jsx-a11y
          - eslint-plugin-import
          - '@typescript-eslint/eslint-plugin'
          - '@typescript-eslint/parser'